spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://database-1.cj0s8o86cjif.ap-southeast-2.rds.amazonaws.com:5432/postgres
    username: postgres
    password: yeon0906!
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org.hibernate.SQL: debug

server:
  port: 8443
  tomcat:
<<<<<<< HEAD
    baseDir: /home/ec2-user/gradproj/grad-project/backend/src/main/resources
  ssl:
    key-store: "classpath:keystore.p12"
    key-store-type: PKCS12
    key-store-password: yeon0906  
=======
    baseDir: /home/ec2-user/gradproj/grad-project/backend/src/main/resources
  ssl:
    key-store: "classpath:keystore.p12"
    key-store-type: PKCS12
    key-store-password: yeon0906
>>>>>>> 4ca2c27347ba89a0368327d99f04bb572fb4e7e7
